version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: klinik_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - klinik
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_NAME: "Web Klinik Gigi"
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: klinik_db
      DB_USERNAME: klinik_user
      DB_PASSWORD: klinik_password

  nginx:
    image: nginx:alpine
    container_name: klinik_nginx
    restart: unless-stopped
    ports:
      - "8000:80"  # Gunakan port 8001 agar tidak bentrok dengan Aplikasi Antrian
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - klinik

  db:
    image: postgres:15
    container_name: klinik_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: klinik_db
      POSTGRES_USER: klinik_user
      POSTGRES_PASSWORD: klinik_password
    volumes:
      - pgdata_klinik:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Gunakan port berbeda jika yang 5432 sudah dipakai
    networks:
      - klinik

networks:
  klinik:
    driver: bridge

volumes:
  pgdata_klinik:
